### ISSUE TITLE
19.5.303 not working

### ISSUE THREAD

**Issue by evanmathis** [eglaubauf/egRedshiftTools#3]
Traceback (most recent call last):
  File "matBuild", line 5, in <module>
  File "/opt/hfs19.5.303/python/lib/python3.9/site-packages-forced/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'materialBuild_RS'

**Comment by eglaubauf** [comment]
Hey @evanmathis , thanks for reporting. This should be resolved now. I also added support for Redshift 3.5. Let me know if that works for you too. 

Best, 
E

**Comment by evanmathis** [comment]
Awesome thank you so much!

It's a great tool, I really appreciate your work on it.
________________________________

**Comment by eglaubauf** [comment]
Thanks, happy to help :)
